### ISSUE TITLE
Cockpit

### ISSUE THREAD

**Issue by algapone** [romapr1me/Sim-Rig-Cockpit#1]

**Comment by rfps06** [comment]
Hey man, i can't open .scene file in MayCad by MayTec, can you send the file again?

**Comment by djpr1me** [comment]
Hi.
Yeah, sure, here's the file.

ср, 5 июл. 2023 г. в 19:31, rfps06 ***@***.***>:

**Comment by djpr1me** [comment]
[pr1me_simrig_rotated_pedals.scene.zip](https://github.com/djpr1me/Sim-Rig-Cockpit/files/11961861/pr1me_simrig_rotated_pedals.scene.zip)
